version: "3.9"
services:
  express:
    container_name: nodetugerente
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:3000
    depends_on:
      - mysqlDatabase
    networks:
      - internalnet
  mysqlDatabase:
    image: mysql:8.0
    container_name: mysqltugerente
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=tugerentedata
      - MYSQL_PASSWORD=root123
      - MYSQL_ROOT_PASSWORD=root123
    ports:
      - 23306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internalnet
volumes:
  mysql-data:
networks:
  internalnet:
    driver: bridge

